# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.3.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

machine:
  node:
    version: 9.3.0
  npm:
    version: 5.6.0

deployment:
  website:
    branch: master
    commands:
      - git config --global user.email "kotakanbe@users.noreply.github.com"
      - git config --global user.name "kotakanbe"
      - echo "machine github.com login kotakanbe password $GITHUB_TOKEN" > ~/.netrc
      - cd website && npm install && GIT_USER=kotakanbe npm run publish-gh-pages

