version: 2
jobs:
  deploy-website:
    working_directory: ~/vuls
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - website-node-modules-{{ checksum "website/yarn.lock" }}
            - website-node-modules-
      - run:
          name: Install node_modules
          command: |
            cd website
            yarn --no-progress
      - run:
          name: Install apt packages
          command: |
            sudo apt install rsync
      - save_cache:
          key: website-node-modules-{{ checksum "website/yarn.lock" }}
          paths:
            - website/node_modules
      - deploy:
          name: Publish gh-pages
          command: |
                  git config --global user.email "kotakanbe@users.noreply.github.com"
                  git config --global user.name "kotakanbe"
                  echo "machine github.com login kotakanbe password $GITHUB_TOKEN" > ~/.netrc
                  cd website && npm install && GIT_USER=kotakanbe npm run publish-gh-pages
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: master
