aliases:
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v1-yarn-{{ .Branch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &filter-only-master
    branches:
      only:
        - master

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages

  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

defaults: &defaults
  working_directory: ~/docusaurus
  docker:
    - image: circleci/node:9.3.0

version: 2
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - run:
          name: Run Test Suites
          command: echo "test"
      - run:
          name: Install Dependencies
          command: sudo apt install rsync
      - run:
          name: Deploy Website
          command: git config --global user.email "kotakanbe@users.noreply.github.com" && git config --global user.name "kotakanbe" && echo "machine github.com login kotakanbe password $GITHUB_TOKEN" > ~/.netrc && cd website && npm install && GIT_USER=kotakanbe npm run publish-gh-pages
      # - run:
          # name: Run Test Suites
          # command: yarn test
      # - run:
          # name: Run Test Suites
          # command: yarn global add docusaurus-init
      # - run:
          # name: Test Static Website Builds
          # command: cd website && yarn run build

  # deploy-website:
    # <<: *defaults
    # steps:
      # - checkout
      # - restore-cache: *restore-yarn-cache
      # - run: *yarn
      # - save-cache: *save-yarn-cache
      # - run:
          # name: Deploy Website
          # commands:
            # - git config --global user.email "kotakanbe@users.noreply.github.com"
            # - git config --global user.name "kotakanbe"
            # - echo "machine github.com login kotakanbe password $GITHUB_TOKEN" > ~/.netrc
            # - cd website && npm install && GIT_USER=kotakanbe npm run publish-gh-pages

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  website:
    jobs:
      - tests:
          filters: *filter-ignore-gh-pages
      # - deploy-website:
          # requires:
            # - tests
          # filters: *filter-only-master

